from IO import *
from meta import *

(File('.doxygen')
 / f'PROJECT_NAME           = "{MODULE}"'
 / f'PROJECT_BRIEF          = "{TITLE}"'
 / r'PROJECT_LOGO           = doc/logo.png'
 / r'OUTPUT_DIRECTORY       = doc'
 / r'HTML_OUTPUT            = html'
 / r'INPUT                  = README.md doc lib inc src hw cpu arch os'
 / r'INCLUDE_PATH           = inc'
 / r'EXCLUDE                = ref/* *.pdf *.djvu'
 / r'EXCLUDE               +=   hw/f4disco/Core   hw/f4disco/Drivers'
 / r'EXCLUDE               +=  hw/pillF103/Core  hw/pillF103/Drivers'
 / r'EXCLUDE               += hw/l496disco/Core hw/l496disco/Drivers'
 / r'WARN_IF_UNDOCUMENTED   = NO'
 / r'RECURSIVE              = YES'
 / r'USE_MDFILE_AS_MAINPAGE = README.md'
 / r'GENERATE_LATEX         = NO'
 / r'FILE_PATTERNS         += *.lex *.yacc *.ragel *.rl'
 / r'EXTENSION_MAPPING      = lex=C++ yacc=C++ ragel=C++ rl=C++ ino=C++'
 / r'HAVE_DOT               = YES'
 / r'EXTRACT_ALL            = YES'
 / r'EXTRACT_STATIC         = YES'
 / r'EXTRACT_PRIVATE        = YES'
 / r'EXTRACT_PACKAGE        = YES'
 / r'EXTRACT_LOCAL_CLASSES  = YES'
 / r'EXTRACT_LOCAL_METHODS  = YES'
 / r'EXTRACT_ANON_NSPACES   = YES'
 / r'LAYOUT_FILE            = doc/DoxygenLayout.xml'
 / r'SORT_GROUP_NAMES       = YES'
 / r'REPEAT_BRIEF           = NO'
 / r'CALL_GRAPH             = YES'
 / r'CALLER_GRAPH           = YES'
 ).sync()
